# Generated by Django 3.0.4 on 2020-09-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='social_media',
            new_name='social_medias',
        ),
    ]
